name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug environment
        run: |
          echo "Current directory: $PWD"
          echo "Directory contents before:"
          ls -la
          echo "Checking if webhook URL is set:"
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            echo "Webhook URL is set"
          else
            echo "Webhook URL is NOT set"
            exit 1
          fi
      
      - name: Inject webhook URL into HTML
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Create a script tag with the webhook URL
          SCRIPT_TAG="<script>window.DISCORD_WEBHOOK_URL = '$WEBHOOK_URL';</script>"
          
          # Insert it right before the closing head tag
          sed -i "s|</head>|$SCRIPT_TAG\n</head>|" index.html
          
          echo "Webhook URL injected into HTML"
          echo "Verifying injection:"
          grep -A 1 "window.DISCORD_WEBHOOK_URL" index.html | sed 's|https://[^"]*|[WEBHOOK_URL_HIDDEN]|'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Debug deployment
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Final directory structure:"
          find . -type f -print
