name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug environment
        run: |
          echo "Checking if webhook URL is set:"
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            echo "Webhook URL is set"
          else
            echo "Webhook URL is NOT set"
            exit 1
          fi
      
      - name: Inject webhook URL into HTML
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "Original head tag position:"
          grep -n "</head>" index.html || echo "Head tag not found"
          
          # Use awk to inject the script tag
          awk '
          BEGIN { found = 0 }
          /<\/head>/ && !found {
            printf "<script>window.DISCORD_WEBHOOK_URL = \"%s\";</script>\n", ENVIRON["WEBHOOK_URL"]
            found = 1
          }
          { print }
          ' index.html > index.html.tmp
          
          # Check if the modification was successful
          if grep -q "window.DISCORD_WEBHOOK_URL" index.html.tmp; then
            mv index.html.tmp index.html
            echo "Successfully injected webhook URL"
            echo "Modified head section (URL hidden):"
            grep -A 2 -B 2 "window.DISCORD_WEBHOOK_URL" index.html | sed 's|https://[^"]*|[WEBHOOK_URL_HIDDEN]|'
          else
            echo "Failed to inject webhook URL"
            exit 1
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Debug deployment
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Final directory structure:"
          find . -type f -print
